### ISSUE TITLE
No module named 'ldm_patched'

### ISSUE THREAD

**Issue by ShockWave2048** [layerdiffusion/sd-forge-layerdiffuse#18]
Hi layerdiffusion!!!
Have some troubles on Windows in A1111 1.8.0
<img width="851" alt="Screenshot_1" src="https://github.com/layerdiffusion/sd-forge-layerdiffusion/assets/800625/8e165db7-629a-4c3b-8195-2f6e1022eaec">

**Comment by wangzijian1010** [comment]
> Hi layerdiffusion!!! Have some troubles on Windows in A1111 1.8.0 <img alt="Screenshot_1" width="851" src="https://private-user-images.githubusercontent.com/800625/309560067-8e165db7-629a-4c3b-8195-2f6e1022eaec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTg4OTcsIm5iZiI6MTcwOTUxODU5NywicGF0aCI6Ii84MDA2MjUvMzA5NTYwMDY3LThlMTY1ZGI3LTYyOWEtNGMzYi04MTk1LTJmNmUxMDIyZWFlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwMjE2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWIxMDBlYWFiZWQ4ZDFlNzA0ZjY4YTgxMjVmYmViNzVlNTdmMTRhZDYzMWUyYjgxYzJhM2QxZjdkNzNhYTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EGb2HkFCWyG6EkAPzoDglcoCv2mp8c2GhuqaOjAHOUM">

same question！

**Comment by huchenlei** [comment]
This extension is for [SD forge](https://github.com/lllyasviel/stable-diffusion-webui-forge).
Original A1111 is not compatible with this extension.

**Comment by udaygiri** [comment]
#18
To fix the ModuleNotFoundError for ldm_patched in your forge_layerdiffusion.py script, follow these steps:

Check Script Requirements: Ensure you've followed any setup or installation instructions that come with the script.

Verify ldm_patched Installation: Make sure any required custom modules or versions, such as ldm_patched, are correctly installed.

Use Correct Python Environment: Confirm you're running the script in the right Python environment where necessary dependencies are installed.

Install Missing Dependencies: If ldm_patched is a separate installation, locate and install it according to provided instructions or documentation.

Check for Typos: Ensure there are no typos in the import statement in your script.

Seek Documentation/Community Help: Look for any installation instructions in the script's documentation or ask for help in related community forums.

Check Path/Environment Variables: Make sure your Python and script paths are correctly set up, including any needed environment variables.

**Comment by wangwenqiao666** [comment]
I have the same question.
![image](https://github.com/layerdiffusion/sd-forge-layerdiffusion/assets/55267900/1678a58e-7592-4c2c-8f92-6799de17365b)

When I update stable diffusion webui, the problem still exists.
![image](https://github.com/layerdiffusion/sd-forge-layerdiffusion/assets/55267900/90b64177-7864-4a66-b225-002ec15f7306)

**Comment by wangwenqiao666** [comment]
I see. We should download the model:
https://pan.quark.cn/s/aba7991d340c#/list/share/e1c768089eac46e287a2facc42c3dc95-layerdiffusion

**Comment by wangzijian1010** [comment]
> I see. We should download the model: https://pan.quark.cn/s/aba7991d340c#/list/share/e1c768089eac46e287a2facc42c3dc95-layerdiffusion

大佬你好 请问将你链接你们的权重下载下来之后 我应该放在那个位置呢 请问

**Comment by Xingeqwd** [comment]
> I see. We should download the model: https://pan.quark.cn/s/aba7991d340c#/list/share/e1c768089eac46e287a2facc42c3dc95-layerdiffusion

oh, man! you are my hero!

**Comment by wangwenqiao666** [comment]
> > I see. We should download the model: https://pan.quark.cn/s/aba7991d340c#/list/share/e1c768089eac46e287a2facc42c3dc95-layerdiffusion
> 
> haha, man! you are my damn hero!

beautiful, did you solve the problem.

**Comment by Xingeqwd** [comment]
> > > I see. We should download the model: https://pan.quark.cn/s/aba7991d340c#/list/share/e1c768089eac46e287a2facc42c3dc95-layerdiffusion
> > 
> > 
> > haha, man! you are my damn hero!
> 
> beautiful, did you solve the problem.

solved, but not this problem, haha

as for me, problem is enviroment problem

this extension has dependence conflict with train tool

i sloved by watching log of booting, find and solve the problem

**Comment by erjihaoshi** [comment]
go https://github.com/lllyasviel/stable-diffusion-webui-forge get ldm_patched   and modules_forge two dirs 
move to your web-ui dir/  
works for me

**Comment by VitoChenLY** [comment]
> go https://github.com/lllyasviel/stable-diffusion-webui-forge get ldm_patched and modules_forge two dirs move to your web-ui dir/ works for me

It also works for me, I can see layerDiffusion in GUI, but it doesn't works.

**Comment by phpseven** [comment]
> 前往https://github.com/lllyasviel/stable-diffusion-webui-forge获取 ldm_patched 和 modules_forge 两个目录 移至你的 web-ui 目录/ 对我有用

it works! 
直接复制进来就行了, 当然模型还是要去下载

**Comment by Grifon75** [comment]
download_### AUTOMATIC1111 stable-diffusion-webui 1.8.0_ then copy with replacement _### stable-diffusion-webui-forge_,You also copy system and venv from your working version there (I have 1.9.4), set the necessary attributes, set _**COMMANDLINE_ARGS=--xformers --cuda-stream**_ and run it. The transparent background works on the models specified in the instructions! Happy launch)

**Comment by bank010** [comment]
> > 去 https://github.com/lllyasviel/stable-diffusion-webui-forge 获取ldm_patched，modules_forge两个目录移动到你的 Web-UI 目录/对我有用
> 
> 它也对我有用，我可以在 GUI 中看到 layerDiffusion，但它不起作用。

你好，找到合适的方法了吗，我也遇到这个问题

**Comment by phpseven** [comment]
> > > 去 https://github.com/lllyasviel/stable-diffusion-webui-forge 获取ldm_patched，modules_forge两个目录移动到你的 Web-UI 目录/对我有用
> > 
> > 
> > 它也对我有用，我可以在 GUI 中看到 layerDiffusion，但它不起作用。
> 
> 你好，找到合适的方法了吗，我也遇到这个问题

用的一键安装包
use this one-click installation package (with git and python included).

[>>> Click Here to Download One-Click Package <<<](https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch21.7z)

**Comment by momognu** [comment]
> > 前往[https://github.com/lllyasviel/stable-diffusion-webui-forge获取](https://github.com/lllyasviel/stable-diffusion-webui-forge%E8%8E%B7%E5%8F%96) ldm_patched 和 modules_forge 两个目录 移至你的 web-ui 目录/ 对我有用
> 
> it works! 直接复制进来就行了, 当然模型还是要去下载

forge主分支已经把ldm_patched这个目录给删掉了，为什么还提示这个错误呢

**Comment by VitoChenLY** [comment]
您的信件已收到，我会尽快回复，谢谢。

**Comment by JiggyDancer** [comment]
Illyasviel Forge no longer has ldm_patched.  You can still access from here:

[https://huggingface.co/spaces/fluxdev/stable-diffusion-webui-forge/tree/main](https://huggingface.co/spaces/fluxdev/stable-diffusion-webui-forge/tree/main)
