### ISSUE TITLE
Question about the result of layerdiffusion

### ISSUE THREAD

**Issue by JZZZ1314** [layerdiffusion/sd-forge-layerdiffuse#33]
In the actual operation process, it was found that the current attention has a significant impact on the generation. Is there anything to pay attention to when filling in prompts? Or is there a sampler? Model? etc., to make the generated results as close as possible
The following example parameters remain consistent
use
![20240304-155359](https://github.com/layerdiffusion/sd-forge-layerdiffusion/assets/104337639/8e383c7a-525e-4ab0-8f7f-8cf5ad8e9426)

not used
![20240304-155355](https://github.com/layerdiffusion/sd-forge-layerdiffusion/assets/104337639/0af65d0b-c55e-48e8-b763-2e759ff48d5c)

**Comment by layerdiffusion** [comment]
currently we only maintain automatic1111 samplers (but may test more implementations in the future)

if using other samplers outside automatic1111, users need to use models with their own risk for any quality degradation

**Comment by huchenlei** [comment]
See https://github.com/huchenlei/ComfyUI-layerdiffusion/issues/5.
