### ISSUE TITLE
Why are image values ​​normalized to [0, 1] instead of [-1, 1]

### ISSUE THREAD

**Issue by xiaohu2015** [layerdiffusion/sd-forge-layerdiffuse#36]
https://github.com/layerdiffusion/sd-forge-layerdiffusion/blob/main/lib_layerdiffusion/utils.py#L7-L10
vae should use [-1, 1] to encode image

**Comment by layerdiffusion** [comment]
https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/b9705c58f66c6fd2c4a0168b26c5cf1fa6c0dde3/modules_forge/forge_loader.py#L239

**Comment by xiaohu2015** [comment]
thanks a lot
