### ISSUE TITLE
Some of the "from foreground to blending" results are not good

### ISSUE THREAD

**Issue by northfoxz** [layerdiffusion/sd-forge-layerdiffuse#37]
Uploaded image
![0175610_PE328883_S5-removebg-preview](https://github.com/layerdiffusion/sd-forge-layerdiffusion/assets/6613987/3faa834a-286a-469f-8bb5-1bff940f26d6)

sofa in the living room, high quality
Negative prompt: bad, ugly
Steps: 20, Sampler: UniPC, CFG scale: 7, Seed: 3720371256, Size: 1024x1024, Model hash: 1fe6c7ec54, Model: juggernautXL_version6Rundiffusion, layerdiffusion_enabled: True, layerdiffusion_method: From Foreground to Blending, layerdiffusion_weight: 1, layerdiffusion_ending_step: 1, layerdiffusion_fg_image: True, layerdiffusion_bg_image: False, layerdiffusion_blend_image: False, layerdiffusion_resize_mode: Crop and Resize,

![New Project (2)](https://github.com/layerdiffusion/sd-forge-layerdiffusion/assets/6613987/c176b8d9-623a-4efb-b1ad-5cba07e3e6a1)

Notes
1. I'm using UniPC sampler as suggested.
2. The sofa in the cropped image wasn't produced by JuggernautXL; it's an actual photograph of a sofa from IKEA.

The resulting images display sofas stacked behind the original sofa. How can we improve the quality of these renders?

Thank you!

**Comment by zombrax1** [comment]
try this 
modern living room, wood floor, big windows, curtain, green hill's view, white walls, rug, high quality
Negative prompt: bad, ugly, sofa
Steps: 20, Sampler: DPM++ 2M SDE Karras, CFG scale: 7, Seed: 4155806341, Size: 1024x704, Model hash: 1fe6c7ec54, Model: juggernautXL_version6Rundiffusion, layerdiffusion_enabled: True, layerdiffusion_method: From Foreground to Blending, layerdiffusion_weight: 1, layerdiffusion_ending_step: 1, layerdiffusion_fg_image: True, layerdiffusion_bg_image: False, layerdiffusion_blend_image: False, layerdiffusion_resize_mode: Crop and Resize, Version: f0.0.17v1.8.0rc-latest-269-gef35383b

**Comment by zombrax1** [comment]
> Uploaded image ![0175610_PE328883_S5-removebg-preview](https://private-user-images.githubusercontent.com/6613987/309759198-3faa834a-286a-469f-8bb5-1bff940f26d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjE5MzksIm5iZiI6MTcwOTU2MTYzOSwicGF0aCI6Ii82NjEzOTg3LzMwOTc1OTE5OC0zZmFhODM0YS0yODZhLTQ2OWYtOGJiNS0xYmZmOTQwZjI2ZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTQxMzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTUxNDg5MzA5MjgzZTk2MTZmZDU4MmY5YTcyYjNhNzE1ZDQyNmUzZDY0NTI3YWY2YzEyM2UxMDBmNWU0OTNhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tCxcFg0EMJJ7bnO_-cYMko81ptdXTWE_HDAWm76YUaQ)
> 
> sofa in the living room, high quality Negative prompt: bad, ugly Steps: 20, Sampler: UniPC, CFG scale: 7, Seed: 3720371256, Size: 1024x1024, Model hash: 1fe6c7ec54, Model: juggernautXL_version6Rundiffusion, layerdiffusion_enabled: True, layerdiffusion_method: From Foreground to Blending, layerdiffusion_weight: 1, layerdiffusion_ending_step: 1, layerdiffusion_fg_image: True, layerdiffusion_bg_image: False, layerdiffusion_blend_image: False, layerdiffusion_resize_mode: Crop and Resize,
> 
> ![New Project (2)](https://private-user-images.githubusercontent.com/6613987/309760244-c176b8d9-623a-4efb-b1ad-5cba07e3e6a1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjE5MzksIm5iZiI6MTcwOTU2MTYzOSwicGF0aCI6Ii82NjEzOTg3LzMwOTc2MDI0NC1jMTc2YjhkOS02MjNhLTRlZmItYjFhZC01Y2JhMDdlM2U2YTEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMTQxMzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWZmYjRlZDBiY2Y0ZmZhMmVkZGY5NjQwNjFhZWVjMjcwNDk0NWNkOWI5ODRmNzJiZDM2ZjU1NzAyYWE4NTljZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DZq6lo-oMiUmiqaqSgPvwb1TovV2uqZE2dr2A1E3-4k)
> 
> Notes
> 
> 1. I'm using UniPC sampler as suggested.
> 2. The sofa in the cropped image wasn't produced by JuggernautXL; it's an actual photograph of a sofa from IKEA.
> 
> The resulting images display sofas stacked behind the original sofa. How can we improve the quality of these renders?
> 
> Thank you!

try this 
modern living room, wood floor, big windows, curtain, green hill's view, white walls, rug, high quality
Negative prompt: bad, ugly, sofa
Steps: 20, Sampler: DPM++ 2M SDE Karras, CFG scale: 7, Seed: 4155806341, Size: 1024x704, Model hash: 1fe6c7ec54, Model: juggernautXL_version6Rundiffusion, layerdiffusion_enabled: True, layerdiffusion_method: From Foreground to Blending, layerdiffusion_weight: 1, layerdiffusion_ending_step: 1, layerdiffusion_fg_image: True, layerdiffusion_bg_image: False, layerdiffusion_blend_image: False, layerdiffusion_resize_mode: Crop and Resize, Version: f0.0.17v1.8.0rc-latest-269-gef35383b

**Comment by zombrax1** [comment]
![Uploading image (7).png…]()

**Comment by zombrax1** [comment]
![image (7)](https://github.com/layerdiffusion/sd-forge-layerdiffusion/assets/50038184/0ed2f9c5-05eb-46f9-909a-8b66f66102fb)

**Comment by northfoxz** [comment]
I see, thank you!
