### ISSUE TITLE
SD1.5

### ISSUE THREAD

**Issue by victorca25** [layerdiffusion/sd-forge-layerdiffuse#5]
How complicated would it be to add support for SD1.5 models?

**Comment by strawberrymelonpanda** [comment]
I'd very much like to see support for SD1.5.

**Comment by sotokisehiro** [comment]
I also strongly hope for support for SD1.5. This will be good news for users including me who are worried about lack of VRAM.
thank you.

**Comment by freecoderwaifu** [comment]
>Models for SD1.5 may be provided later if demanded.

Demand +1.

**Comment by akaSurreal** [comment]
+1

**Comment by jordanjay29** [comment]
More support for SD1.5 here, this would become a vital component of my workflow!

**Comment by edtjulien** [comment]
I would love to have it for SD 1.5 too!

**Comment by fai-9** [comment]
I am eagerly awaiting the SD1.5 model, as I do not have the environment to comfortably run SDXL.

**Comment by git-uniqity** [comment]
is there any possibility to combine Xadapter and Layerdiffussion?

**Comment by QunBB** [comment]
<img width="798" alt="image" src="https://github.com/layerdiffusion/sd-forge-layerdiffuse/assets/51054082/0baa88f1-3c46-4fd4-858c-2b010499a0f5">

Demand +1. Respect!

**Comment by mbastias** [comment]
First, thanks for the extension, looks awesome. Second, I'm asking politely, demand sounds harsh, for 1.5 models.

**Comment by toyxyz** [comment]
Demand +1

**Comment by albertocasanova** [comment]
My SD 1.5 support request << this is!

**Comment by sotokisehiro** [comment]
We welcome support for SD1.5.
My deepest respect and gratitude to all the development members!!!

**Comment by freecoderwaifu** [comment]
SD 1.5 models work as expected, thank you. Looking forward to img2img and the merged pull request to auto save the transparent images.

**Comment by victorca25** [comment]
Thanks for the quick addition! It works great, I will close the ticket.
