### ISSUE TITLE
poor quality with layerdiffusion enabled

### ISSUE THREAD

**Issue by carlmoss22** [layerdiffusion/sd-forge-layerdiffuse#79]
same easy prompt with juggernaut v6 - pic is looking good, with layerdiffusion enabled it looks bad. unsharp and very rough.

the same result on some other models. 

could it be that some models don't work with layerdiffusion?

**Comment by zhucede** [comment]
XL models can get better result.

**Comment by cha0sbuster** [comment]
From my own experience, the less lineage your model has in common with the base model of your version, the worse results you'll have.
**I'm speculating here,** but I imagine the LD models might expect that the weights look a certain way to work properly. Models like Juggernaut V6 are merges, which have blends of different training sessions inside them, meaning a lot of the (network) layers are more different from the base models than a trained checkpoint. Try using either the base model or a trained checkpoint.
Perhaps something like an LCM-style LoRA, or some other solution that generalizes better, could alleviate this, but LD _is_ an experimental project still.

> XL models can get better result.
Juggernaut _is_ an XL model. I haven't personally noticed much difference between XL and 1.5, only between merges and trained checkpoints
