### ISSUE TITLE
Only the checkboard image is saved to output folder

### ISSUE THREAD

**Issue by SLAPaper** [layerdiffusion/sd-forge-layerdiffuse#9]
How to automatically save the transparent image?

**Comment by SLAPaper** [comment]
It seems that fixed by https://github.com/layerdiffusion/sd-forge-layerdiffusion/pull/6

**Comment by EtienneDosSantos** [comment]
> It seems that fixed by #6

Can confirm the fix works. Just make sure to enable the checkbox under 'Settings > Layer Diffusion'.

**Comment by AlekFy** [comment]
Would be great if the setting come to the master branch, the need to save every file manually if really frustrating, otherwise - great work, thank you!

**Comment by NutritiousCookie** [comment]
Sorry; why is this closed? I'm still getting checkerboards.

**Comment by AlekFy** [comment]
can we ask to pull this fix into the main branch? I have the latest version but there is no setting for layered diff in the settings section :(

**Comment by SLAPaper** [comment]
@NutritiousCookie @AlekFy checkout the PR #6 and continue discussion there

**Comment by zffffff** [comment]
> > It seems that fixed by #6
> 
> Can confirm the fix works. Just make sure to enable the checkbox under 'Settings > Layer Diffusion'.

there is no layer diffusion in setting tab

**Comment by LordeOfTheFries** [comment]
Yeah it seems that commit was never applied or whatever. Downloading the .py files and manually adding/replacing them in your install seems to be a bad idea, as it's an old version of the file and you'll lose options and might run into errors.
Why was this closed? I just spent way too much time looking for an option that doesn't exist, and then trying to add it in.
